// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlgen_tutorial

type Klinik struct {
	IDKlinik        *int    `json:"ID_KLINIK"`
	KlnkBezeichnung *string `json:"KLNK_BEZEICHNUNG"`
	KlnkName        *string `json:"KLNK_NAME"`
	KlnkCode        *string `json:"KLNK_CODE"`
	KlnkNameCustom  *string `json:"KLNK_NAME_CUSTOM"`
}
